### ISSUE TITLE
In case of simpler usage, is the package recommend?

### ISSUE THREAD

**Issue by john-bonachon** [ashleysommer/sanic-cors#10]
I wonder if `CORS(app)` is different in terms of performance, than just returning `access-control-allow-origin:*` in response headers. Supposing I only have one view,

```
...
     return json(data, headers={"access-control-allow-origin": "*"})
```

**Comment by ashleysommer** [comment]
@john-bonachon 
Depends on how configurable you want your CORS responses to be.
In your case, with a single view, if you just want the headers to contain `{"access-control-allow-origin": "*"}` and you want to return this to all clients, then your simple example is higher performance.

The power of Sanic-CORS (and Flask-CORS from which it was derived), is how you can customise it to work differently for different routes and different views, as well as its simple configuration. If you don't need that, then your simple method works fine.

**Comment by ashleysommer** [comment]
Closing because question was answered, and no reply in 7 days.
