### ISSUE TITLE
unhandled RequestTimeout exceptions

### ISSUE THREAD

**Issue by r7ar7a** [ashleysommer/sanic-cors#11]
https://github.com/ashleysommer/sanic-cors/blob/master/sanic_cors/extension.py#L177

When a 'keep-alive' connection reaches timeout, Sanic raises an RequestTimeout exception. This case the `wrapped_function` gets `None` for `req`. The result is an `AttributeError: 'NoneType' object has no attribute 'url'`. Moreover the original handler doesn't get a chance for proper handling because of the raised `AttributeError`

**Comment by ashleysommer** [comment]
Thanks for bringing this up!
This is similar to another bug I've seen when a different exception is not handled properly.
I will probably need to do better error-case checking.
Bug-fix incoming.

**Comment by ashleysommer** [comment]
Fixed in https://github.com/ashleysommer/sanic-cors/commit/ff1449dfc796746192bbb9c6c7c42196ec7c647a
