### ISSUE TITLE
"Fix" updates shouldn't change "minor" requirements.

### ISSUE THREAD

**Issue by Rulox** [ashleysommer/sanic-cors#25]
Hi, this is more a suggestion, not really an issue.

(For this example, versioning like X.Y.Z will be X=major, Y=minor, Z=fix)

In your last "fix" release, you have updated sanic requirement to 0.8.1. This means, you have changed a minor version of a requirement in a non-breaking release.

If someone has the 0.9.* in their requirements, and they have set the sanic-version to 0.7.*, this will cause an error. 

I think, fix changes should only include fix versions updated in requirements (minor -> minors and major -> majors), to avoid breaking changes when you only want to update a fix version.

Thanks!

**Comment by ashleysommer** [comment]
Thanks for your report.

Enumerated rebuttal:

1) Sanic-CORS doesn't use Semantic-Versioning, the is no meaning behind each of dot-separated parts of the package version.
2) Sanic-CORS is considered alpha software, breaking changes should be anticipated (but not necessarily exist) on every release, despite the version number.
3) The Sanic project doesn't use Semantic-Versioning either. Moving from from Sanic 0.7.0 to 0.8.1 doesn't mean anything, except that it is a newer version. In fact the jump from 0.7.x to 0.8.x was likely just to signify the large length of time between the two releases.
Any project upgrading from Sanic 0.7.0 to 0.8.1 shoud not consider that a breaking change.
4) Why would someone want to run the latest Sanic-CORS but stay on Sanic 0.7.0? That doesn't make sense. Historically Sanic-CORS has always tracked the newest released version of Sanic, and as such relies on the newest version as a requirement. If you install the newest version of Sanic-CORS, expect that it _will_ list the newest version of Sanic in its requirements.

Not saying you're wrong, your opinion is perfectly valid. In a perfect world all software would be semantically versioned and adhere to semantic version conventions. There would be consistent release cycles, comprehensive changelings, and hobby projects would eventually leave Alpha status.

This is not that world.

**Comment by Rulox** [comment]
Hey, thanks for the quick feedback!

It makes sense it's a perfect valid response. 

About the number 4, a reason would be the same. If Sanic makes a mistake and they introduce a breaking change in a "patch" release, all of your systems might break. Normally you let the last number on `*` only for non-breaking changes and minor fixes. As you said, that's in a world where everyone uses semantic (or similar) versioning it would make sense. To be honest, I don't see why you would use 3 numbers for your versioning and not using something like semantic, if the numbers don't mean anything, just use 1 or 2 (X.Y). But that's my opinion.

I guess we'll just create our own lib or move to a different one then to avoid these kind of problems in the future.

Closing this issue as everything is clear. Thanks again!
