### ISSUE TITLE
Fix init_app method

### ISSUE THREAD

**Issue by junhoyeo** [ashleysommer/sanic-cors#29]
How about fixing `init_app` method to behave like the original `flask-cors` and other Sanic extensions?

I got the following error when using the following code: 
`CORS().init_app(_app)`

```
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from server import app
  File "/Users/junhoyeo/dimigo-petitions-back/server/__init__.py", line 16, in <module>
    app = create_app()
  File "/Users/junhoyeo/dimigo-petitions-back/server/__init__.py", line 12, in create_app
    CORS().init_app(_app)
  File "/usr/local/lib/python3.7/site-packages/sanic_cors/extension.py", line 161, in init_app
    app = context.app
AttributeError: 'Sanic' object has no attribute 'app'
```

**Comment by ashleysommer** [comment]
Sanic-cors is built using Sanic-Plugins-Framework. Therefore, the `init_app()` method expects slightly different arguments than in traditional Flask plugins.

Can you give more details about your use case? Why are you calling `init_app()`.
Can you simply call `CORS(app)`?

**Comment by junhoyeo** [comment]
Oops, I was so accustomed to Flask that I did not know about the Sanic-Plugins-Framework structure.
Well, `CORS (app)` seems to be enough, since I doesn't have any other obvious reason for that; Was just curious why `CORS().init_app()`do not behave like `flask-cors` 😉
I'll try to look more about the Sanic-Plugins-Framework. 
Thanks and sorry for the answer and your time. 
(You can close this issue)

**Comment by ashleysommer** [comment]
Can you tell me more about where you've seen the `CORS().init_app()` pattern before?
I've used Flask for a long time and used a lot of Flask plugins, but I've never need to call `init_app()` before.

See the Flask-CORS official documentation here:
https://flask-cors.readthedocs.io/en/latest/
This is the code snippet:
```
from flask import Flask
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

@app.route("/")
def helloWorld():
  return "Hello, cross-origin-world!"
```

Sanic-Plugins-Framework is designed to create plugins which are friendly to users coming from a Flask background, so snippets like the above from Flask-CORS works perfectly fine in Sanic-CORS.

**Comment by ashleysommer** [comment]
@junhoyeo 
I'm going to close this issue because I believe it is resolved. Please reopen it if you have any more problems.
