### ISSUE TITLE
OPTIONS still executes methods 

### ISSUE THREAD

**Issue by mikepc** [ashleysommer/sanic-cors#30]
The OPTIONS preflight request is intended to NOT execute the endpoint, placing this on the endpoint causes the endpoint to be executed on the pre-flight request (so a web client would then double-execute the same endpoint).

The idea of pre-flight is that it's a check to see if the method CAN be executed, not to actually execute it.

**Comment by ashleysommer** [comment]
@mikepc 
If you enable `automatic_options` configurable setting in Sanic-CORS, then the plugin will automatically handle the pre-flight request and return the correct response to the client without executing your route function.

If however you don't use `automatic_options`, and instead add add the `OPTIONS` method on your route handler then your route handler will be executed and its up to your code to check if its OPTIONS or not and handle the request appropriately.

I hope that clears things up.

**Comment by ashleysommer** [comment]
@mikepc  I'm going to close this Issue. If you have any more problems, please reopen it.

**Comment by adamshamsudeen** [comment]
Why can't we add `automatic_options` to the **basic usage** example in the docs?

**Comment by ashleysommer** [comment]
I thought it was already in there.

If it's not, we absolutely should add it.
