### ISSUE TITLE
Compatibility with Sanic 19.6.2

### ISSUE THREAD

**Issue by tng10** [ashleysommer/sanic-cors#31]
Hi,

I just bumped into an error when upgrading to newest version of Sanic using ASGI interface.

Since ASGI lifespan protocol has support for only two server events, we no longer can make usage of `before_server_start` and `after_server_stop` server events.

Sanic CORS uses `before_server_start` server event and this give us the following warning:
```
UserWarning: You have set a listener for "before_server_start" in ASGI mode. It will be executed as early as possible, but not before the ASGI server is started.
```

Do you think we can come up with a workaround for this case?

**Comment by ashleysommer** [comment]
Thank you for reporting this.

I haven't tested the new Sanic release using ASGI yet, but I suspected it might cause an incompatibility like this.

For now, lets just say this plugin (and probably lots of other Sanic plugins/extensions) are not compatible with ASGI mode. I will add this to the readme.

I will definitely look into coming up with a fix.

**Comment by ashleysommer** [comment]
@tng10 
That was easier than I expected.
I've pushed a fix, can you test version `0.9.8.post3` to see if it has solved your problem?

**Comment by tng10** [comment]
@ashleysommer thanks for the quick response.

Yes, I can confirm. It does work. Thanks again!

As you mentioned there are some other Sanic plugins that needs to be updated in order to compatible with ASGI, which is the case of `pytest-sanic` and `sanic-openapi`. I'll ping them about this.

**Comment by ashleysommer** [comment]
Fixed in https://github.com/ashleysommer/sanic-cors/commit/2f96a8323a1991dc9bc037b5157726e9844759e4
