### ISSUE TITLE
Latest Sanic removed sanic.server.CIDict

### ISSUE THREAD

**Issue by benjolitz** [ashleysommer/sanic-cors#33]
This bugfix breaks the entire library: https://github.com/huge-success/sanic/commit/b397637bb979566183116b2663ec2c1ef02246a9

Suggestion:

Update https://github.com/ashleysommer/sanic-cors/blob/2f96a8323a1991dc9bc037b5157726e9844759e4/sanic_cors/core.py#L13-L17 to look like 
```
try:
    from sanic.compat import Header as CIMultiDict
except ImportError:
    try:
        from sanic.server import CIMultiDict
    except ImportError:
        from sanic.server import CIDict as CIMultiDict
```

**Comment by trentmurray** [comment]
Are you going to put a pull request in for the above change @benjolitz ?

**Comment by ashleysommer** [comment]
Fixed via https://github.com/ashleysommer/sanic-cors/commit/187726f81493dc0d2974bc67597cb9786324c02b
