### ISSUE TITLE
nameError: name 'CIMultiDict' is not defined

### ISSUE THREAD

**Issue by ruifernando7** [ashleysommer/sanic-cors#34]
For Sanic 19.6.3

**Comment by ruifernando7** [comment]
i'm currently using sanic-cors version 0.9.9

**Comment by trentmurray** [comment]
Stack trace confirming this issue.

```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/sanic/app.py", line 985, in handle_request
request, response
File "/usr/local/lib/python3.7/site-packages/spf/framework.py", line 579, in _run_response_middleware
_response = await _response
File "/usr/local/lib/python3.7/site-packages/sanic_cors/extension.py", line 267, in unapplied_cors_response_middleware
set_cors_headers(req, resp, context, res_options)
File "/usr/local/lib/python3.7/site-packages/sanic_cors/core.py", line 254, in set_cors_headers
headers_to_set = get_cors_headers(options, req.headers, req.method)
File "/usr/local/lib/python3.7/site-packages/sanic_cors/core.py", line 175, in get_cors_headers
headers = CIMultiDict()
NameError: name 'CIMultiDict' is not defined

```

**Comment by contrivable** [comment]
I have a proposal for a patch including some clean up around it and deprecation warnings.
I do not know how test_consistent_origin_concat is supposed to work and how to fix it. It did fail here with sanic 19.6.2 and 19.6.3 respectively.

Changeset:
* Use Header instead CIDict/CIMultiDict
* Fix deprecated assertEquals
* Change re.compile inputs to raw strings
* Change to explicit imports
* Change to set literals as opposed to set() calls
* Attempt to improve test_consistent_origin_concat

[sanic_19_6_3_patch.txt](https://github.com/ashleysommer/sanic-cors/files/3532841/sanic_19_6_3_patch.txt)

**Comment by ashleysommer** [comment]
I've pushed a quick patch to get v0.9.9 working.
https://github.com/ashleysommer/sanic-cors/commit/e982802f6e405f798514bdd57622dda21423fea4
I definitely want to get this fixed up properly for future releases.
Thank you for your contributions.

**Comment by jkanche** [comment]
https://github.com/huge-success/sanic/issues/1663#issue-487029019
suggests to change imports to 

`from multidict import CIMultiDict`
