### ISSUE TITLE
CORS with Redirect 302

### ISSUE THREAD

**Issue by snguyenthanh** [ashleysommer/sanic-cors#39]
Hi,

I have a `Sanic` app that serves as a proxy to redirect requests to other `Sanic` apps. All of them have `Sanic-CORS` enabled.

The issue is, when the client's browser fails the response on redirecting:

```
Access to XMLHttpRequest at 'http://192.168.1.141:8080/socket.io/?EIO=3&transport=polling&t=MuxKoy8' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

Is there a way to use CORS with redirect 302 ?

**Comment by ashleysommer** [comment]
Hi @snguyenthanh 
I think this is a fundamental CORS issue, not specifically Sanic-CORS.

See this django-cors issue from 2013 with the same problem: https://github.com/adamchainz/django-cors-headers/issues/17

What you _could_ do, is use sanic-CORS with "automatic_options" turned off. Then in your route handler, check the 'request.method' property, if the method is "OPTIONS" then return an empty http response with status 200 (sanic-cors should automatically add the CORS headers to that), or if its not method "OPTIONS", then respond with your 302.

**Comment by snguyenthanh** [comment]
Thank you for your reply, @ashleysommer .

> What you _could_ do, is use sanic-CORS with "automatic_options" turned off. Then in your route handler, check the 'request.method' property, if the method is "OPTIONS" then return an empty http response with status 200 (sanic-cors should automatically add the CORS headers to that), or if its not method "OPTIONS", then respond with your 302.

I will take note of this approach and try next time.

My hackish workaround is to return a cookie with an unique identifier ID for the machine that the request should be redirected to, and let the load balancer do its job of redirecting the request rather than the browser.
