### ISSUE TITLE
Sanic 19.12 breaks sanic-cors

### ISSUE THREAD

**Issue by aymanbagabas** [ashleysommer/sanic-cors#40]
https://github.com/huge-success/sanic/issues/1749

**Comment by ashleysommer** [comment]
Hi @aymanbagabas
Thanks for this report!
Please see my post on huge-success/sanic#1749 for a detailed response.
I will leave this issue open until a fix is ready.
I've created an upstream issue in SPF here: https://github.com/ashleysommer/sanicpluginsframework/issues/15

**Comment by ashleysommer** [comment]
Update: Sanic-CORS 0.10.0.b1 is released with Sanic 19.12 compatibility

Install using PIP with `--pre` like this:
`pip3 install --pre "sanic-cors>0.9.99"`

**Comment by ashleysommer** [comment]
Fixed by https://github.com/ashleysommer/sanic-cors/commit/fce6f003bbb7a27f8478a3c8374e2f8d6682d3cb
