### ISSUE TITLE
documentation links

### ISSUE THREAD

**Issue by abuckenheimer** [ashleysommer/sanic-cors#6]
Hey I noticed none of your documentation links work, are the http://sanic-cors.corydolphin.com/en/latest/* pages in progress or did you mean to point to http://flask-cors.corydolphin.com/en/latest/* ?

**Comment by ashleysommer** [comment]
@abuckenheimer Thanks for pointing that out.

There are no eternal docs for sanic-cors.
Those links are simply the `http://flask-cors.corydolphin.com/en/latest/*` links after replacing all occurrances (project wide) of `flask-cors` with `sanic-cors`.

As you mention, it means those links are broken and don't resolve to anything. The only documentation for Sanic-Cors is the README.md and the examples.

Perhaps it is best to just remove mention of documentation links.

**Comment by cayetanobv** [comment]
IMHO: as you say @ashleysommer, the best option to avoid confusion is remove mention of documentation links.
