### ISSUE TITLE
Vary header added again and not appended to existing

### ISSUE THREAD

**Issue by opatut** [ashleysommer/sanic-cors#62]
If I set a `Vary` header in my handler, then I get a response with two of those headers, one from me and one with `Vary: Origin` from sanic-cors. According [to MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary), the Vary header should be a comma-separated list of header names, and not appear multiple times.

Please append `, Origin` to the `Vary` header if it already exists.

**Comment by ashleysommer** [comment]
Hi @opatut 
Sorry for the delay. This is fixed in the latest Sanic-CORS release, v2.2.0.
