### ISSUE TITLE
Bug: Sanic app fails to start when using sanic-cors

### ISSUE THREAD

**Issue by damianj** [ashleysommer/sanic-cors#63]
App fails to start with the following error:

```bash
Traceback (most recent call last):
  File "/app/app.py", line 176, in <module>
  create_app().run()
  File "/app/app.py", line 149, in create_app
  CORS(app)
  File "/usr/local/lib/python3.10/site-packages/sanic_cors/extension.py", line 163, in __init__
  super(CORS, self).__init__(app, config)
  TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

Wasn't having issues before and issues started after the latest release of Sanic.

**Comment by damianj** [comment]
Actually I think the issue stems from this PR in sanic-ext: https://github.com/sanic-org/sanic-ext/commit/943ef076e9eb54264dfbc1f68c7c9246861fcd08#diff-be3233a6b970a8b434e428faf4c680858d508e71124fe39ca063d1c944db29a4L36-L40

**Comment by damianj** [comment]
Just for more context, I have confirmed that is is some incompatibility with the latest version of sanic/sanic-ext, if I freeze the packages to the following versions everything works as expected.

```
sanic==22.3.2
sanic-ext==22.3.2
Sanic-Cors==2.0.1
```

**Comment by ashleysommer** [comment]
Hi @damianj 
> Does this mean this repo will no longer be maintained

This project will still be maintained. The CORS functionality of sanic-ext is quite basic, it doesn't have the level of features and configuration that the Sanic-CORS extension has.
If you just need basic CORS enablement in your Sanic project, then I definitely recommend to use sanic-ext.
However, for users who do not wish to enable sanic-ext (it is pretty heavy with a bunch of bundled features, and not everyone will want to install sanic-ext), or for people who want the extra Sanic-CORS features and configuration, then I recommend to use Sanic-CORS.

I will push out an update today that fixes Sanic-CORS to work with newer Sanic-ext versions.

**Comment by ashleysommer** [comment]
@damianj There is a new release sanic-cors v2.1.0 that addresses this issue.
