### ISSUE TITLE
Missing CORS headers in response with latest sanic 22.9.0

### ISSUE THREAD

**Issue by philipnbbc** [ashleysommer/sanic-cors#64]
It appears that sanic_cors (2.1.0) with the latest version of sanic (22.9.0) fails to add CORS headers when combined with other response middleware .

The test code provided below demonstrates the issue.

Run with `TEST_WITH_OTHER_MIDDLEWARE = False` and `curl -i http://127.0.0.1:8000` returns `Access-Control-Allow-Origin: *`. Run it with `TEST_WITH_OTHER_MIDDLEWARE = True` and that header is not returned.

Installing sanic<22.9 results in the CORS header being returned in both cases.

```python
from sanic import Sanic
from sanic.response import json
from sanic_cors import CORS

TEST_WITH_OTHER_MIDDLEWARE = True

app = Sanic("my-hello-world-app")

async def other_response_middleware(request, response):
    return None

@app.route('/')
async def test(request):
    return json({'hello': 'world'})

CORS(app)
if TEST_WITH_OTHER_MIDDLEWARE:
    # This results in no "Access-Control-Allow-Origin: *" header
    app.register_middleware(other_response_middleware, "response")

if __name__ == '__main__':
    app.run()
```

**Comment by ashleysommer** [comment]
Hi @philipnbbc 
Thanks for the bug report.

Sanic-CORS plugin does not yet work with the recently released Sanic v22.9.

It is common when new versions of Sanic come out that it can take several weeks for third-party plugins to updated to include compatibility with the new version.

I am the only developer on this project and have not had a chance to look into Sanic v22.9 yet, or the changes that would be required to add compatibility to Sanic-CORS.

**Comment by philipnbbc** [comment]
Thanks @ashleysommer, I appreciate all your efforts developing and maintaining sanic-cors. It's not an immediate problem for us and we can pin to the previous Sanic version.

**Comment by ashleysommer** [comment]
@philipnbbc 
I've released a beta version of sanic-cors that should have compatibility with Sanic v22.9+
Can you please install sanic-cors v2.2.0b1 and test if it fixes the problem for you?

**Comment by philipnbbc** [comment]
Tested and it works. Thanks!
