### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by ragizo** [ashleysommer/sanic-cors#9]
I tried to implement sanic-cors but it does not work. I got a 405 Method not allowed status (OPTIONS).
here is my implementation
```python
# some code
CORS(app)

@app.delete('/api/auth')
@auth.login_required
async def auth_logout(request):
    auth.logout_user(request)
    return json(None, status=OK)
```
I use Sanic 0.5.4 and Sanic-cors 0.5.4.2

Can you share how to solve it please?

Notes : Just for information I use fetch (isomorphic-fetch) in my client (React). I think it is not related but just to give some context to the issue :)

**Comment by ragizo** [comment]
curiously, I found a trick that make it works. I think the issue is about I use @app.delete helper and have no entry with OPTIONS method for my path.
The trick I used add just and handler for OPTIONS method for each path I use (I don't use OPTIONS explicitly so it works for me).
Here is the code:
```python
def manage_cors(app):
    def option_handler(request):
        from sanic.response import text
        return text('', status=200)

    routes = set([k for k, v in app.router.routes_all.items()])
    for route in routes:
        app.add_route(option_handler, route, methods=["OPTIONS"])
```
The issue can be closed (or you can re open it it you have some better way to solve my problem) :)

**Comment by ashleysommer** [comment]
Hello @ragizo 
You can use the `automatic_options` configuration parameter to handle the OPTIONS response automatically for you.

For example:
```
CORS(app, automatic_options=True)
@app.delete('/api/auth')
@auth.login_required
async def auth_logout(request):
    auth.logout_user(request)
    return json(None, status=OK)
```
_OR_ _(with the app config key)_
```
app = Sanic(__name__)
app.config['CORS_AUTOMATIC_OPTIONS'] = True
CORS(app)
@app.delete('/api/auth')
@auth.login_required
async def auth_logout(request):
    auth.logout_user(request)
    return json(None, status=OK)
```
_OR_ _(directly on the route with the cors decorator)_
```
@app.delete('/api/auth')
@auth.login_required
@cross_origin(app, automatic_options=True)
async def auth_logout(request):
    auth.logout_user(request)
    return json(None, status=OK)
```

**Comment by ragizo** [comment]
It works ;) Thanks a lot for reply 👍
